services:
  coshi.amazon_transcoder.transcoder:
      class: Coshi\Bundle\TranscodeBundle\Transcoder\Transcoder
      arguments:
            - "@service_container"
            - "@aws_s3.client"
            - "@coshi.amazon_transcoder.elastict_transcoder_client"
  coshi.amazon_transcoder.s3client:
          class:   Aws\S3\S3Client
          factory: [Aws\S3\S3Client, factory]
          arguments:
              - { key: "%aws_access_key_id%", secret: "%aws_secret_key%" }
  coshi.amazon_transcoder.elastict_transcoder_client:
          class: Aws\ElasticTranscoder\ElasticTranscoderClient
          factory: [Aws\ElasticTranscoder\ElasticTranscoderClient, factory]
          arguments:
              -
                credentials:
                    key: %amazon_s3.key%
                    secret: %amazon_s3.secret%
                region: %amazon_s3.region%
                version: latest
